apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: triage-hub
  namespace: argocd
spec:
  description: "Triage Hub App Project"
  sourceRepos:
    - https://github.com/X-BRAIN-CDO-09/Triage-Hub.git
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
