apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-engine-secrets
  namespace: triage-hub
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ai-engine-secrets
    creationPolicy: Owner
  data:
    - secretKey: BEDROCK_MODEL
      remoteRef:
        key: triage-hub/ai-engine
        property: BEDROCK_MODEL
    - secretKey: SERVICE_AUTO_TOKEN_BLOCK
      remoteRef:
        key: triage-hub/ai-engine
        property: SERVICE_AUTO_TOKEN_BLOCK
    - secretKey: WEBSOCK_URL
      remoteRef:
        key: triage-hub/ai-engine
        property: WEBSOCK_URL
    - secretKey: SQS_QUEUE_URL
      remoteRef:
        key: triage-hub/ai-engine
        property: SQS_QUEUE_URL
