apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf1-worker
  namespace: triage-hub
  labels:
    app: tf1-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf1-worker
  template:
    metadata:
      labels:
        app: tf1-worker
    spec:
      serviceAccountName: tf1-worker-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ai-worker
          image: 730335441285.dkr.ecr.us-east-1.amazonaws.com/tf1-worker:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "512m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          env:
            - name: AIOPS_OBSERVABILITY_ENABLED
              value: "true"
            - name: SQS_WAIT_SECONDS
              value: "5"
            - name: SQS_MAX_MESSAGES
              value: "1"
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: ai-engine-secrets
                  key: SQS_QUEUE_URL
            - name: BEDROCK_MODEL
              valueFrom:
                secretKeyRef:
                  name: ai-engine-secrets
                  key: BEDROCK_MODEL
            - name: SERVICE_AUTO_TOKEN_BLOCK
              valueFrom:
                secretKeyRef:
                  name: ai-engine-secrets
                  key: SERVICE_AUTO_TOKEN_BLOCK
            - name: WEBSOCK_URL
              valueFrom:
                secretKeyRef:
                  name: ai-engine-secrets
                  key: WEBSOCK_URL
