// =============================================================================
// jira-dispatcher Lambda
// Giai đoạn 1: Tạo Jira Ticket (Unassigned) + lưu mapping DynamoDB
// Giai đoạn 3: Xử lý Slack callback (Confirm & Assign)
//
// Trigger: API Gateway POST /slack
// Flow GĐ1: Nhận alert payload → tạo Jira ticket → lưu mapping DynamoDB
// Flow GĐ3: Nhận Slack callback → verify signature → assign Jira → audit
// =============================================================================

const { DynamoDBClient, PutItemCommand, GetItemCommand } = require("@aws-sdk/client-dynamodb");
const { SecretsManagerClient, GetSecretValueCommand } = require("@aws-sdk/client-secrets-manager");
const crypto = require("crypto");

const dynamoClient = new DynamoDBClient({});
const secretsClient = new SecretsManagerClient({});

// Environment variables (set by Terraform)
const DYNAMODB_TABLE = process.env.DYNAMODB_TABLE;
const JIRA_SECRET_ARN = process.env.JIRA_SECRET_ARN;
const SLACK_SIGNING_SECRET_ARN = process.env.SLACK_SIGNING_SECRET_ARN;

// Cache secrets trong warm Lambda container
let cachedJiraSecret = null;
let cachedSlackSigningSecret = null;

// =============================================================================
// Helper: Lấy secret từ AWS Secrets Manager (có cache)
// =============================================================================
async function getSecret(secretArn) {
  const command = new GetSecretValueCommand({ SecretId: secretArn });
  const response = await secretsClient.send(command);
  return response.SecretString;
}

async function getJiraSecret() {
  if (cachedJiraSecret) return cachedJiraSecret;
  const raw = await getSecret(JIRA_SECRET_ARN);
  cachedJiraSecret = JSON.parse(raw); // { email, token, base_url }
  return cachedJiraSecret;
}

async function getSlackSigningSecret() {
  if (cachedSlackSigningSecret) return cachedSlackSigningSecret;
  cachedSlackSigningSecret = await getSecret(SLACK_SIGNING_SECRET_ARN);
  return cachedSlackSigningSecret;
}

// =============================================================================
// GĐ 1: Tạo Jira Ticket qua REST API
// =============================================================================
async function createJiraTicket(jiraCreds, alertPayload) {
  const { email, token, base_url } = jiraCreds;

  // Basic auth: email:token → base64
  const auth = Buffer.from(`${email}:${token}`).toString("base64");

  const ticketPayload = {
    fields: {
      project: {
        key: alertPayload.ownership?.jira_project || "TRIAGE",
      },
      summary: `[${(alertPayload.alert?.severity || "unknown").toUpperCase()}] ${alertPayload.alert?.title || alertPayload.alert?.service || "New Incident"}`,
      description: {
        type: "doc",
        version: 1,
        content: [
          {
            type: "paragraph",
            content: [
              {
                type: "text",
                text: `Incident ID: ${alertPayload.incident_id || "N/A"}\nService: ${alertPayload.alert?.service || "unknown"}\nSeverity: ${alertPayload.alert?.severity || "unknown"}\nDescription: ${alertPayload.alert?.description || "No description"}\n\nGenerated by Triage Hub AI System.`,
              },
            ],
          },
        ],
      },
      issuetype: {
        name: "Bug",
      },
      labels: ["ai-triage", alertPayload.tenant_id || "unknown-tenant"],
    },
  };

  console.log("Creating Jira ticket:", JSON.stringify(ticketPayload));

  const response = await fetch(`${base_url}/rest/api/3/issue`, {
    method: "POST",
    headers: {
      Authorization: `Basic ${auth}`,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(ticketPayload),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    console.error("Jira API error:", response.status, errorBody);
    throw new Error(`Jira API error ${response.status}: ${errorBody}`);
  }

  const result = await response.json();
  console.log("Jira ticket created:", result.key, result.id);

  return {
    issueKey: result.key,     // e.g. "TRIAGE-42"
    issueId: result.id,       // e.g. "10042"
    self: result.self,        // API URL
  };
}

// =============================================================================
// GĐ 1: Lưu mapping incident → Jira issue vào DynamoDB
// =============================================================================
async function saveJiraMapping(incidentId, tenantId, alertId, jiraResult) {
  const command = new PutItemCommand({
    TableName: DYNAMODB_TABLE,
    Item: {
      PK: { S: `TENANT#${tenantId}` },
      SK: { S: `INCIDENT#${incidentId}` },
      incident_id: { S: incidentId },
      tenant_id: { S: tenantId },
      alert_id: { S: alertId || "unknown" },
      jira_issue_key: { S: jiraResult.issueKey },
      jira_issue_id: { S: jiraResult.issueId },
      status: { S: "UNASSIGNED" },
      created_at: { S: new Date().toISOString() },
    },
  });

  await dynamoClient.send(command);
  console.log("Jira mapping saved to DynamoDB:", `TENANT#${tenantId}`, `INCIDENT#${incidentId}`);
}

// =============================================================================
// GĐ 3: Verify Slack Request Signature
// =============================================================================
function verifySlackSignature(signingSecret, requestBody, timestamp, signature) {
  // Reject stale requests (> 5 phút)
  const now = Math.floor(Date.now() / 1000);
  if (Math.abs(now - parseInt(timestamp)) > 300) {
    console.warn("Slack request timestamp is stale");
    return false;
  }

  const sigBasestring = `v0:${timestamp}:${requestBody}`;
  const mySignature = "v0=" + crypto
    .createHmac("sha256", signingSecret)
    .update(sigBasestring, "utf8")
    .digest("hex");

  return crypto.timingSafeEqual(
    Buffer.from(mySignature, "utf8"),
    Buffer.from(signature, "utf8")
  );
}

// =============================================================================
// GĐ 3: Assign Jira Ticket
// =============================================================================
async function assignJiraTicket(jiraCreds, issueKey, accountId) {
  const { email, token, base_url } = jiraCreds;
  const auth = Buffer.from(`${email}:${token}`).toString("base64");

  const response = await fetch(`${base_url}/rest/api/3/issue/${issueKey}/assignee`, {
    method: "PUT",
    headers: {
      Authorization: `Basic ${auth}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ accountId }),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`Jira assign error ${response.status}: ${errorBody}`);
  }

  console.log(`Jira ticket ${issueKey} assigned to ${accountId}`);
}

// =============================================================================
// GĐ 3: Lưu audit trail khi user bấm nút trên Slack
// =============================================================================
async function saveCallbackAudit(incidentId, tenantId, slackUserId, action, issueKey) {
  const command = new PutItemCommand({
    TableName: DYNAMODB_TABLE,
    Item: {
      PK: { S: `TENANT#${tenantId}` },
      SK: { S: `AUDIT#${incidentId}#${Date.now()}` },
      incident_id: { S: incidentId },
      tenant_id: { S: tenantId },
      jira_issue_key: { S: issueKey || "unknown" },
      action: { S: action },
      slack_user_id: { S: slackUserId },
      actioned_at: { S: new Date().toISOString() },
    },
  });

  await dynamoClient.send(command);
}

// =============================================================================
// Main Handler — Route theo loại event
// =============================================================================
exports.handler = async (event) => {
  console.log("jira-dispatcher invoked. Event:", JSON.stringify(event));

  try {
    // =========================================================================
    // Route 1: Slack Interactive Callback (GĐ 3)
    // Slack gửi POST với body là "payload=..." (URL-encoded)
    // =========================================================================
    const rawBody = event.body || "";

    if (rawBody.startsWith("payload=") || (event.headers && event.headers["x-slack-signature"])) {
      return await handleSlackCallback(event);
    }

    // =========================================================================
    // Route 2: Direct invoke / API Gateway tạo Jira ticket (GĐ 1)
    // =========================================================================
    return await handleCreateTicket(event);

  } catch (err) {
    console.error("jira-dispatcher error:", err);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: err.message }),
    };
  }
};

// =============================================================================
// Handler: GĐ 1 — Tạo Jira Ticket
// =============================================================================
async function handleCreateTicket(event) {
  // Parse payload
  let alertPayload;
  if (event.body) {
    alertPayload = typeof event.body === "string" ? JSON.parse(event.body) : event.body;
  } else {
    alertPayload = event;
  }

  const incidentId = alertPayload.incident_id || alertPayload.correlation_id || `inc-${Date.now()}`;
  const tenantId = alertPayload.tenant_id || "unknown";
  const alertId = alertPayload.alert?.alert_id || "unknown";

  // 1. Lấy Jira credentials từ Secrets Manager
  const jiraCreds = await getJiraSecret();

  // 2. Tạo Jira ticket
  const jiraResult = await createJiraTicket(jiraCreds, alertPayload);

  // 3. Lưu mapping vào DynamoDB
  await saveJiraMapping(incidentId, tenantId, alertId, jiraResult);

  return {
    statusCode: 201,
    body: JSON.stringify({
      status: "ticket_created",
      incident_id: incidentId,
      jira_issue_key: jiraResult.issueKey,
    }),
  };
}

// =============================================================================
// Handler: GĐ 3 — Slack Callback (Confirm & Assign)
// =============================================================================
async function handleSlackCallback(event) {
  const rawBody = event.body || "";
  const headers = event.headers || {};

  // 1. Verify Slack Signature
  if (SLACK_SIGNING_SECRET_ARN) {
    const signingSecret = await getSlackSigningSecret();
    const timestamp = headers["x-slack-request-timestamp"] || headers["X-Slack-Request-Timestamp"];
    const signature = headers["x-slack-signature"] || headers["X-Slack-Signature"];

    if (!timestamp || !signature || !verifySlackSignature(signingSecret, rawBody, timestamp, signature)) {
      console.error("Slack signature verification failed");
      return { statusCode: 401, body: "Unauthorized" };
    }
  }

  // 2. Parse Slack payload
  const decoded = decodeURIComponent(rawBody.replace("payload=", ""));
  const payload = JSON.parse(decoded);

  const action = payload.actions?.[0];
  const slackUserId = payload.user?.id || "unknown";
  const slackUserName = payload.user?.name || "unknown";

  if (!action) {
    return { statusCode: 200, body: "No action found" };
  }

  console.log("Slack action received:", action.action_id, "by user:", slackUserName);

  // 3. Parse action value
  let actionValue;
  try {
    actionValue = JSON.parse(action.value);
  } catch {
    actionValue = { incident_id: action.value };
  }

  const incidentId = actionValue.incident_id || "unknown";
  const issueKey = actionValue.jira_issue_key;
  const tenantId = actionValue.tenant_id || "unknown";

  // 4. Handle từng loại action
  if (action.action_id === "assign_incident_action") {
    // Confirm & Assign — dùng suggested_assignee từ AI
    const assigneeAccountId = actionValue.suggested_assignee_account_id;

    if (issueKey && assigneeAccountId) {
      const jiraCreds = await getJiraSecret();
      await assignJiraTicket(jiraCreds, issueKey, assigneeAccountId);
    }

    await saveCallbackAudit(incidentId, tenantId, slackUserId, "CONFIRM_ASSIGN", issueKey);

    // Cập nhật Slack message
    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        replace_original: true,
        text: `✅ Ticket ${issueKey || "N/A"} assigned by <@${slackUserId}>. (Confirmed AI suggestion)`,
      }),
    };
  }

  if (action.action_id === "self_assign_incident_action") {
    // Self-assign — cần lấy Jira account ID từ Slack user mapping
    // Hiện tại chỉ lưu audit, vì cần mapping Slack → Jira account
    await saveCallbackAudit(incidentId, tenantId, slackUserId, "SELF_ASSIGN", issueKey);

    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        replace_original: true,
        text: `🙋 Ticket ${issueKey || "N/A"} self-assigned by <@${slackUserId}>.`,
      }),
    };
  }

  // Action không xác định
  return { statusCode: 200, body: "OK" };
}
