// =============================================================================
// jira-dispatcher Lambda
// Giai đoạn 1: Tạo Jira Ticket (Unassigned) + lưu mapping DynamoDB
// Giai đoạn 3: Xử lý Slack callback (Confirm & Assign)
//
// Trigger: API Gateway POST /slack
// Flow GĐ1: Nhận alert payload → tạo Jira ticket → lưu mapping DynamoDB
// Flow GĐ3: Nhận Slack callback → verify signature → assign Jira → audit
// =============================================================================

const { DynamoDBClient, PutItemCommand, GetItemCommand } = require("@aws-sdk/client-dynamodb");
const { SecretsManagerClient, GetSecretValueCommand } = require("@aws-sdk/client-secrets-manager");
const crypto = require("crypto");

// Timeout mặc định cho các request HTTP bên ngoài (ms)
const EXTERNAL_API_TIMEOUT_MS = 10000;

const dynamoClient = new DynamoDBClient({});
const secretsClient = new SecretsManagerClient({});

// Environment variables (set by Terraform)
const DYNAMODB_TABLE = process.env.DYNAMODB_TABLE;
const JIRA_SECRET_ARN = process.env.JIRA_SECRET_ARN;
const SLACK_SIGNING_SECRET_ARN = process.env.SLACK_SIGNING_SECRET_ARN;

// Cache secrets trong warm Lambda container
let cachedJiraSecret = null;
let cachedSlackSigningSecret = null;

// =============================================================================
// Helper: Lấy secret từ AWS Secrets Manager (có cache)
// =============================================================================
async function getSecret(secretArn) {
  const command = new GetSecretValueCommand({ SecretId: secretArn });
  const response = await secretsClient.send(command);
  return response.SecretString;
}

async function getJiraSecret() {
  if (cachedJiraSecret) return cachedJiraSecret;
  const raw = await getSecret(JIRA_SECRET_ARN);
  cachedJiraSecret = JSON.parse(raw); // { email, token, base_url }
  return cachedJiraSecret;
}

async function getSlackSigningSecret() {
  if (cachedSlackSigningSecret) return cachedSlackSigningSecret;
  cachedSlackSigningSecret = await getSecret(SLACK_SIGNING_SECRET_ARN);
  return cachedSlackSigningSecret;
}

// =============================================================================
// GĐ 1: Tạo Jira Ticket qua REST API
// =============================================================================
async function createJiraTicket(jiraCreds, alertPayload) {
  const { email, token, base_url } = jiraCreds;

  // Basic auth: email:token → base64
  const auth = Buffer.from(`${email}:${token}`).toString("base64");

  const ticketPayload = {
    fields: {
      project: {
        key: alertPayload.ownership?.jira_project || "TRIAGE",
      },
      summary: `[${(alertPayload.alert?.severity || "unknown").toUpperCase()}] ${alertPayload.alert?.title || alertPayload.alert?.service || "New Incident"}`,
      description: {
        type: "doc",
        version: 1,
        content: [
          {
            type: "paragraph",
            content: [
              {
                type: "text",
                text: `Incident ID: ${alertPayload.incident_id || "N/A"}\nService: ${alertPayload.alert?.service || "unknown"}\nSeverity: ${alertPayload.alert?.severity || "unknown"}\nDescription: ${alertPayload.alert?.description || "No description"}\n\nGenerated by Triage Hub AI System.`,
              },
            ],
          },
        ],
      },
      issuetype: {
        name: "Bug",
      },
      labels: ["ai-triage", alertPayload.tenant_id || "unknown-tenant"],
    },
  };

  console.log("Creating Jira ticket for incident:", alertPayload.incident_id, "project:", alertPayload.ownership?.jira_project);

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), EXTERNAL_API_TIMEOUT_MS);

  let response;
  try {
    response = await fetch(`${base_url}/rest/api/3/issue`, {
      method: "POST",
      headers: {
        Authorization: `Basic ${auth}`,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify(ticketPayload),
      signal: controller.signal,
    });
  } finally {
    clearTimeout(timeout);
  }

  if (!response.ok) {
    const errorBody = await response.text();
    console.error("Jira API error:", response.status);
    throw new Error(`Jira API error: status ${response.status}`);
  }

  const result = await response.json();
  console.log("Jira ticket created:", result.key, result.id);

  return {
    issueKey: result.key,     // e.g. "TRIAGE-42"
    issueId: result.id,       // e.g. "10042"
    self: result.self,        // API URL
  };
}

// =============================================================================
// GĐ 1: Reserve mapping trước khi tạo Jira (idempotent via conditional write)
// =============================================================================
async function reserveIncidentMapping(incidentId, tenantId, alertId) {
  const command = new PutItemCommand({
    TableName: DYNAMODB_TABLE,
    Item: {
      PK: { S: `TENANT#${tenantId}` },
      SK: { S: `INCIDENT#${incidentId}` },
      incident_id: { S: incidentId },
      tenant_id: { S: tenantId },
      alert_id: { S: alertId || "unknown" },
      status: { S: "PENDING" },
      created_at: { S: new Date().toISOString() },
    },
    ConditionExpression: "attribute_not_exists(PK)",
  });

  await dynamoClient.send(command);
  console.log("Incident reserved in DynamoDB:", `TENANT#${tenantId}`, `INCIDENT#${incidentId}`);
}

// =============================================================================
// GĐ 1: Cập nhật mapping sau khi Jira ticket tạo thành công
// =============================================================================
async function updateJiraMapping(incidentId, tenantId, jiraResult) {
  const command = new PutItemCommand({
    TableName: DYNAMODB_TABLE,
    Item: {
      PK: { S: `TENANT#${tenantId}` },
      SK: { S: `INCIDENT#${incidentId}` },
      incident_id: { S: incidentId },
      tenant_id: { S: tenantId },
      jira_issue_key: { S: jiraResult.issueKey },
      jira_issue_id: { S: jiraResult.issueId },
      status: { S: "UNASSIGNED" },
      created_at: { S: new Date().toISOString() },
    },
  });

  await dynamoClient.send(command);
  console.log("Jira mapping updated in DynamoDB:", `TENANT#${tenantId}`, `INCIDENT#${incidentId}`);
}

// =============================================================================
// GĐ 3: Verify Slack Request Signature
// =============================================================================
function verifySlackSignature(signingSecret, requestBody, timestamp, signature) {
  // Reject stale requests (> 5 phút)
  const now = Math.floor(Date.now() / 1000);
  if (Math.abs(now - parseInt(timestamp)) > 300) {
    console.warn("Slack request timestamp is stale");
    return false;
  }

  const sigBasestring = `v0:${timestamp}:${requestBody}`;
  const mySignature = "v0=" + crypto
    .createHmac("sha256", signingSecret)
    .update(sigBasestring, "utf8")
    .digest("hex");

  // timingSafeEqual throws khi length khác nhau → guard trước
  const myBuf = Buffer.from(mySignature, "utf8");
  const theirBuf = Buffer.from(signature, "utf8");
  if (myBuf.length !== theirBuf.length) return false;

  return crypto.timingSafeEqual(myBuf, theirBuf);
}

// =============================================================================
// GĐ 3: Assign Jira Ticket
// =============================================================================
async function assignJiraTicket(jiraCreds, issueKey, accountId) {
  const { email, token, base_url } = jiraCreds;
  const auth = Buffer.from(`${email}:${token}`).toString("base64");

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), EXTERNAL_API_TIMEOUT_MS);

  let response;
  try {
    response = await fetch(`${base_url}/rest/api/3/issue/${issueKey}/assignee`, {
      method: "PUT",
      headers: {
        Authorization: `Basic ${auth}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ accountId }),
      signal: controller.signal,
    });
  } finally {
    clearTimeout(timeout);
  }

  if (!response.ok) {
    console.error(`Jira assign error: status ${response.status}`);
    throw new Error(`Jira assign error: status ${response.status}`);
  }

  console.log(`Jira ticket ${issueKey} assigned to ${accountId}`);
}

// =============================================================================
// GĐ 3: Lưu audit trail khi user bấm nút trên Slack
// =============================================================================
async function saveCallbackAudit(incidentId, tenantId, slackUser, actionType, issueKey, assigneeJiraId, status) {
  const timestamp = Math.floor(Date.now() / 1000);
  const command = new PutItemCommand({
    TableName: DYNAMODB_TABLE,
    Item: {
      PK: { S: `TENANT#${tenantId}#INCIDENT#${incidentId}` },
      SK: { S: `AUDIT#${timestamp}` },
      incident_id: { S: incidentId },
      tenant_id: { S: tenantId },
      jira_issue_key: { S: issueKey || "unknown" },
      action_type: { S: actionType },
      approver_slack_id: { S: slackUser.id },
      approver_slack_name: { S: slackUser.name },
      assigned_jira_id: { S: assigneeJiraId || "unknown" },
      status: { S: status },
      actioned_at: { S: new Date().toISOString() },
    },
  });

  await dynamoClient.send(command);
}

// =============================================================================
// Main Handler — Route theo loại event
// =============================================================================
exports.handler = async (event) => {
  console.log("jira-dispatcher invoked. Route:", event.headers?.["x-slack-signature"] ? "slack-callback" : "create-ticket");

  try {
    // =========================================================================
    // Route 1: Slack Interactive Callback (GĐ 3)
    // Slack gửi POST với body là "payload=..." (URL-encoded)
    // =========================================================================
    const rawBody = event.body || "";

    if (rawBody.startsWith("payload=") || (event.headers && event.headers["x-slack-signature"])) {
      return await handleSlackCallback(event);
    }

    // =========================================================================
    // Route 2: Direct invoke / API Gateway tạo Jira ticket (GĐ 1)
    // =========================================================================
    return await handleCreateTicket(event);

  } catch (err) {
    console.error("jira-dispatcher error:", err.message);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: "Internal server error" }),
    };
  }
};

// =============================================================================
// Handler: GĐ 1 — Tạo Jira Ticket
// =============================================================================
async function handleCreateTicket(event) {
  // Parse payload
  let alertPayload;
  if (event.body) {
    alertPayload = typeof event.body === "string" ? JSON.parse(event.body) : event.body;
  } else {
    alertPayload = event;
  }

  const incidentId = alertPayload.incident_id || alertPayload.correlation_id;
  if (!incidentId) {
    return {
      statusCode: 400,
      body: JSON.stringify({ error: "Missing incident_id or correlation_id" }),
    };
  }
  const tenantId = alertPayload.tenant_id || "unknown";
  const alertId = alertPayload.alert?.alert_id || "unknown";

  // 1. Reserve DynamoDB mapping trước (idempotent — nếu đã tồn tại thì trả về existing)
  try {
    await reserveIncidentMapping(incidentId, tenantId, alertId);
  } catch (err) {
    if (err.name === "ConditionalCheckFailedException") {
      console.log("Incident already exists, returning existing mapping:", incidentId);
      const existing = await dynamoClient.send(new GetItemCommand({
        TableName: DYNAMODB_TABLE,
        Key: { PK: { S: `TENANT#${tenantId}` }, SK: { S: `INCIDENT#${incidentId}` } },
      }));
      return {
        statusCode: 200,
        body: JSON.stringify({
          status: "already_exists",
          incident_id: incidentId,
          jira_issue_key: existing.Item?.jira_issue_key?.S || "pending",
        }),
      };
    }
    throw err;
  }

  // 2. Lấy Jira credentials từ Secrets Manager
  const jiraCreds = await getJiraSecret();

  // 3. Tạo Jira ticket
  const jiraResult = await createJiraTicket(jiraCreds, alertPayload);

  // 4. Cập nhật mapping với Jira issue key
  await updateJiraMapping(incidentId, tenantId, jiraResult);

  return {
    statusCode: 201,
    body: JSON.stringify({
      status: "ticket_created",
      incident_id: incidentId,
      jira_issue_key: jiraResult.issueKey,
    }),
  };
}

// =============================================================================
// GĐ 3: Gọi Slack response_url để cập nhật message gốc
// =============================================================================
async function updateSlackMessage(responseUrl, updatedBlocks) {
  try {
    const response = await fetch(responseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        replace_original: true,
        blocks: updatedBlocks,
      }),
    });

    if (!response.ok) {
      console.error("Slack response_url error:", response.status);
    } else {
      console.log("Slack message updated successfully via response_url");
    }
  } catch (err) {
    // Non-fatal: Jira assignment đã thành công, chỉ Slack UI chưa cập nhật
    console.error("Failed to update Slack message (non-fatal):", err.message);
  }
}

// =============================================================================
// Handler: GĐ 3 — Slack Callback (Confirm & Assign)
// =============================================================================
async function handleSlackCallback(event) {
  const rawBody = event.body || "";
  const headers = event.headers || {};

  // 1. Verify Slack Signature (fail-closed: bắt buộc có signing secret)
  if (!SLACK_SIGNING_SECRET_ARN) {
    console.error("SLACK_SIGNING_SECRET_ARN is not configured — rejecting request");
    return { statusCode: 500, body: "Server misconfiguration" };
  }

  const signingSecret = await getSlackSigningSecret();
  const timestamp = headers["x-slack-request-timestamp"] || headers["X-Slack-Request-Timestamp"];
  const signature = headers["x-slack-signature"] || headers["X-Slack-Signature"];

  if (!timestamp || !signature || !verifySlackSignature(signingSecret, rawBody, timestamp, signature)) {
    console.error("Slack signature verification failed");
    return { statusCode: 401, body: "Unauthorized" };
  }

  // 2. Parse Slack payload (Slack gửi x-www-form-urlencoded)
  const params = new URLSearchParams(rawBody);
  const payloadStr = params.get("payload");
  if (!payloadStr) {
    console.error("Missing payload field in Slack callback body");
    return { statusCode: 400, body: "Bad Request: missing payload" };
  }

  let payload;
  try {
    payload = JSON.parse(payloadStr);
  } catch {
    console.error("Invalid JSON in Slack callback payload");
    return { statusCode: 400, body: "Bad Request: invalid payload" };
  }

  const action = payload.actions?.[0];
  const slackUserId = payload.user?.id || "unknown";
  const slackUserName = payload.user?.username || payload.user?.name || "unknown";
  const slackUser = { id: slackUserId, name: slackUserName };
  const responseUrl = payload.response_url;

  if (!action) {
    return { statusCode: 200, body: "No action found" };
  }

  console.log("Slack action received:", action.action_id, "by user:", slackUserName);

  // 3. Parse action value
  let actionValue;
  try {
    actionValue = JSON.parse(action.value);
  } catch {
    actionValue = { incident_id: action.value };
  }

  const incidentId = actionValue.incident_id || "unknown";
  const issueKey = actionValue.jira_issue_key;
  const tenantId = actionValue.tenant_id || "unknown";

  // 4. Handle từng loại action
  if (action.action_id === "assign_incident_action") {
    // Confirm & Assign — dùng suggested_assignee từ AI
    const assigneeAccountId = actionValue.suggested_assignee_account_id;
    let status = "SUCCESS";
    let jiraCreds;

    if (issueKey && assigneeAccountId) {
      jiraCreds = await getJiraSecret();
      try {
        await assignJiraTicket(jiraCreds, issueKey, assigneeAccountId);
      } catch (err) {
        console.error("Assign Error:", err);
        status = "FAILED_API";
      }
    } else {
      status = "MISSING_INFO";
    }

    await saveCallbackAudit(incidentId, tenantId, slackUser, "CONFIRM_ASSIGN", issueKey, assigneeAccountId, status);

    // Lấy thông tin assignee từ Jira để hiển thị tên
    let assigneeName = assigneeAccountId || "N/A";
    let jiraBaseUrl = "";
    if (jiraCreds && assigneeAccountId) {
      jiraBaseUrl = jiraCreds.base_url;
      try {
        const auth = Buffer.from(`${jiraCreds.email}:${jiraCreds.token}`).toString("base64");
        const userResp = await fetch(`${jiraCreds.base_url}/rest/api/3/user?accountId=${encodeURIComponent(assigneeAccountId)}`, {
          method: "GET",
          headers: { Authorization: `Basic ${auth}`, Accept: "application/json" },
        });
        if (userResp.ok) {
          const userData = await userResp.json();
          const name = userData.displayName || assigneeAccountId;
          const email = userData.emailAddress ? ` (${userData.emailAddress})` : "";
          assigneeName = `${name}${email}`;
        }
      } catch (err) {
        console.warn("Failed to fetch assignee name:", err.message);
      }
    }

    // Build Jira ticket link
    const jiraLink = issueKey && jiraBaseUrl
      ? `<${jiraBaseUrl}/browse/${issueKey}|${issueKey}>`
      : (issueKey || "N/A");

    // Cập nhật Slack message qua response_url (xóa nút bấm, thêm trạng thái)
    const originalBlocks = payload.message?.blocks || [];
    const updatedBlocks = originalBlocks.filter(b => b.type !== "actions");
    updatedBlocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `✅ *Assigned!*\n• *Ticket:* ${jiraLink}\n• *Assigned to:* ${assigneeName}\n• *Confirmed by:* <@${slackUserId}>`
      }
    });

    if (responseUrl) {
      await updateSlackMessage(responseUrl, updatedBlocks);
    }

    return { statusCode: 200, body: "" };
  }

  if (action.action_id === "self_assign_incident_action") {
    // Self-assign — cần lấy Jira account ID từ Slack user mapping
    // Hiện tại chỉ lưu audit, vì cần mapping Slack → Jira account
    await saveCallbackAudit(incidentId, tenantId, slackUser, "SELF_ASSIGN", issueKey, "pending_lookup", "PENDING");

    // Cập nhật Slack message qua response_url (xóa nút bấm)
    const originalBlocks = payload.message?.blocks || [];
    const updatedBlocks = originalBlocks.filter(b => b.type !== "actions");
    updatedBlocks.push({
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: `🙋 *Ticket ${issueKey || "N/A"}* was self-assigned by <@${slackUserId}>.`
        }
      ]
    });

    if (responseUrl) {
      await updateSlackMessage(responseUrl, updatedBlocks);
    }

    return { statusCode: 200, body: "" };
  }

  // Action không xác định
  return { statusCode: 200, body: "OK" };
}
