apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sigstore-policy-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://sigstore.github.io/helm-charts
    targetRevision: 0.10.6
    chart: policy-controller
    helm:
      values: |
        cosign:
          cosignWebhook:
            imagePolicy:
              create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cosign-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: policy.sigstore.dev
      jsonPointers:
        - /webhooks
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: policy.sigstore.dev
      jsonPointers:
        - /webhooks



