apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: triage-hub-app
  namespace: argocd
spec:
  project: triage-hub
  source:
    repoURL: https://github.com/X-BRAIN-CDO-09/Triage-Hub.git
    targetRevision: develop
    path: capstone/tf-1/devops/platform/overlays/sandbox
  destination:
    server: https://kubernetes.default.svc
    namespace: triage-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
