apiVersion: v1
kind: Service
metadata:
  name: prometheus-operated
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9000
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-operated
  namespace: monitoring
subsets:
  - addresses:
      - ip: 32.194.212.107
    ports:
      - name: http
        port: 9000
        protocol: TCP
