apiVersion: v1
kind: Service
metadata:
  name: prometheus-operated
  namespace: monitoring
spec:
  type: ExternalName
  externalName: ec2-54-86-176-17.compute-1.amazonaws.com
  ports:
    - name: http
      port: 9090
      targetPort: 9000
      protocol: TCP
